"""Dependency-free structural checks; these do not replace Odoo integration tests."""
import ast
import csv
from pathlib import Path
import subprocess
import shutil
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
ADDON = ROOT / 'custom_addons' / 'fleetflow'


def main():
    manifest = ast.literal_eval((ADDON / '__manifest__.py').read_text())
    assert manifest['version'].startswith('16.0.')
    assert set(manifest['depends']) == {'web', 'fleet', 'mail'}
    for path in manifest['data']:
        assert (ADDON / path).is_file(), path
    for assets in manifest['assets'].values():
        for asset in assets:
            assert (ADDON.parent / asset).is_file(), asset
    py_files = list(ADDON.rglob('*.py')) + list((ROOT / 'fleetflow').glob('*.py'))
    for path in py_files:
        ast.parse(path.read_text(), filename=str(path))
    xml_files = list(ADDON.rglob('*.xml'))
    roots = [ET.parse(path).getroot() for path in xml_files]
    ids = set()
    for root in roots:
        for element in root.iter():
            if 'id' in element.attrib:
                identifier = element.attrib['id']
                assert identifier not in ids, identifier
                ids.add(identifier)
    ids.add('model_fleetflow_order')  # Generated by Odoo's model registry.
    for root in roots:
        for element in root.iter():
            for key in ('ref', 'parent', 'action'):
                ref = element.attrib.get(key)
                if ref and ('.' not in ref or ref.startswith('fleetflow.')):
                    assert ref.removeprefix('fleetflow.') in ids, ref
    with (ADDON / 'security/ir.model.access.csv').open() as stream:
        acls = list(csv.DictReader(stream))
    for acl in acls:
        assert acl['group_id:id'] in ids
        assert all(acl[k] in {'0', '1'} for k in ('perm_read', 'perm_write', 'perm_create', 'perm_unlink'))
    model_tree = ast.parse((ADDON / 'models.py').read_text())
    methods = {node.name for node in ast.walk(model_tree) if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))}
    for root in roots:
        for button in root.iter('button'):
            if button.attrib.get('type') == 'object':
                assert button.attrib['name'] in methods
    assert '.env' in (ROOT / 'fleetflow/.gitignore').read_text().splitlines(), 'Ignore generated secrets.'
    if shutil.which('node'):
        subprocess.run(['node', '--input-type=module', '--check'], input=(ADDON / 'static/src/workspace.js').read_text(), text=True, check=True)
    print(f'PASS: {len(py_files)} Python files, {len(xml_files)} XML files, manifest assets, XML references, {len(acls)} ACL entries and workflow buttons.')
    print('Odoo installation, database rules, browser behaviour and concurrency are NOT tested by this script.')


if __name__ == '__main__':
    main()
